apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: innovatech
resources:
  - namespace.yml
  - mysql.yml
  - service-mysql.yml
  - backend.yml
  - service-backend.yml
  - frontend.yml
  - service-frontend.yml
  - autoscaling.yml
