apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-ventas-data
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-despacho-data
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-ventas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-ventas
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-ventas
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: root-password
            - name: MYSQL_DATABASE
              value: ventas_db
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command: [sh, -c, "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-ventas-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-despacho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-despacho
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-despacho
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: root-password
            - name: MYSQL_DATABASE
              value: despacho_db
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command: [sh, -c, "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD"]
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-despacho-data
